import pandas as pd 
import matplotlib.pyplot as plt
df = pd.read_csv(r'C:\Users\GOURAV SHARMA\OneDrive\Documents\real_projects\car_sales_data.csv')
print(df.describe())
print(df.duplicated())
print(df.isnull())
top_10cars_sold = df['Model'].value_counts().head(10)
print(top_10cars_sold)
total_sales = df['Manufacturer'].value_counts()
plt.figure(figsize = (7,8))
plt.bar(total_sales.index ,total_sales.values , color = 'green',label = 'Total sales of each manufacturer')
plt.legend()
plt.xlabel('Manufaturer')
plt.ylabel('Number of cars delivered')
plt.show()
cars_sold = df['Fuel type'].value_counts()
plt.figure(figsize = (7,8))
plt.pie(cars_sold, labels = cars_sold.index , autopct = '%.1f%%' , startangle= 90 )
plt.show()
car_prices = df['Price'].value_counts()
plt.figure(figsize = (7,8))
plt.hist(df['Price'], bins= 30 ,color = 'purple',edgecolor = 'black')
plt.show()
df['profit'] = df['Price']*0.1
print(df['profit'].min())
print(df['profit'].max())
print(df['profit'].mean())
df['profit'].plot(kind = 'box',vert = False , figsize = (6,7))
plt.show()
plt.figure(figsize = (7,8))
plt.scatter(df['Engine size'],df['Price'],color = 'blue' , marker = '^' , label = 'Price per engine size')
plt.legend()
plt.show()
bins = [0,20000,60000,df['Mileage'].max()]
labels = ['Low','Mid','High']
df['Mileage_group'] = pd.cut(df['Mileage'],bins = bins , labels = labels)
df['Mileage_group'].value_counts().sort_index()
plt.figure(figsize = (7,8))
plt.bar(df['Mileage_group'].values , df['Mileage_group'].index , color = 'yellow' )
plt.show()
