import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv(r'C:\Users\GOURAV SHARMA\Downloads\amazon_sales.csv')
print(df.isnull().sum())
print(df.duplicated().sum())
Top10_products = df['Product'].value_counts().head(10)
print(Top10_products)
# Now I am going to make a bar chart of quantity and price on the basis of city
df['total_sales'] = df['Price'] * df['Quantity']
print(df['total_sales'])
city_sales = df.groupby('City')['total_sales'].sum()
plt.figure(figsize = (8,5))
plt.bar(city_sales.index,city_sales.values,color = 'yellow', label = 'Total sales on the basis of city')
plt.title("sales per city")
plt.xlabel('cities')
plt.ylabel('Sales')
plt.tight_layout()
plt.savefig('Bar graph of sales as per city')
plt.show()
payment_method = df['PaymentMethod'].value_counts()
plt.figure(figsize = (8,8))
plt.pie(payment_method , labels = payment_method.index , autopct= '%1.1f%%',startangle= 90)
plt.title('Pie chart on the basis of Payment Method')
plt.tight_layout
plt.savefig('payemnt_method.png')
plt.show()
plt.figure(figsize = (7,8))
plt.hist(df['Profit'],bins=30,color='black',edgecolor = 'red')
plt.title('Profit in ranges')
plt.xlabel('Profit Range')
plt.ylabel('Profit')
plt.tight_layout()
plt.show()
print(df['Profit'].mean())
print(df['Profit'].max())
print(df.columns)
print(df['Date'].unique()[:20])
df['Date'] = pd.to_datetime(df['Date'])
df['Month'] = df['Date'].dt.to_period('M')
month_sales = df.groupby('Month')['total_sales'].sum()
plt.figure(figsize=(8,6))
plt.plot(month_sales.index.astype(str), month_sales.values, marker='o', color='blue')
plt.title('Month-wise Sales Trend')
plt.xlabel('Month')
plt.ylabel('Total Sales')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

